# options for analysis running
run:
  timeout: 2m

# output configuration options
output:
  # sorts results by: filepath, line and column
  sort-results: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - bodyclose
    - errname
    - gochecknoglobals
    - gochecknoinits
    - gomnd
    - loggercheck
    - revive

# all available settings of specific linters
linters-settings:
  gosimple:
    # Select the Go version to target. The default is '1.13'.
    go: "1.18"

  staticcheck:
    # Select the Go version to target. The default is '1.13'.
    go: "1.18"
    checks: ["all"]

  stylecheck:
    # Select the Go version to target. The default is '1.13'.
    go: "1.18"

  unused:
    # Select the Go version to target. The default is '1.13'.
    go: "1.18"

  revive:
    enable-all-rules: true
    rules:
      - name: imports-blacklist
        severity: error
        disabled: false
        arguments:
          - "log"
      - name: function-result-limit
        severity: warning
        disabled: false
        arguments: [2]
      - name: function-length
        disabled: false
        severity: warning
        arguments: [10, 0]
      - name: file-header
        disabled: true
        arguments:
          - This is the text that must appear at the top of source files.
      - name: line-length-limit
        severity: warning
        disabled: false
        arguments: [80]
      - name: argument-limit
        severity: warning
        disabled: false
        arguments: [4]
      - name: banned-characters
        disabled: true
        arguments: ["Ω", "Σ", "σ", "7"]
      - name: cyclomatic
        severity: warning
        disabled: false
        arguments: [3]
      - name: cognitive-complexity
        severity: warning
        disabled: false
        arguments: [7]
      - name: max-public-structs
        severity: warning
        disabled: false
        arguments: [3]
