# options for analysis running
run:
  timeout: 2m

# output configuration options
output:
  # sorts results by: filepath, line and column
  sort-results: true

linters:
  enable:
    - deadcode
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - varcheck

# all available settings of specific linters
linters-settings:
  gosimple:
    # Select the Go version to target. The default is '1.13'.
    go: "1.18"

  staticcheck:
    # Select the Go version to target. The default is '1.13'.
    go: "1.18"
    checks: ["all"]

  stylecheck:
    # Select the Go version to target. The default is '1.13'.
    go: "1.18"

  unused:
    # Select the Go version to target. The default is '1.13'.
    go: "1.18"

  depguard:
    list-type: blacklist
    include-go-root: true
    packages:
      - log
    packages-with-error-message:
      # specify an error message to output when a blacklisted package is used
      - log: "logging is handled by github.com/sirupsen/logrus"
