name: "Golang code checks"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  format:
    name: format go files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18.1
      - name: Format
        working-directory: ./backend
        run: gofmt -l -d -s .
  lint:
    name: lint go files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18.1
      - name: Run linter
        uses: golangci/golangci-lint-action@v3
        with:
          args: --config ./backend/.golangci.yaml
          version: latest
  build:
    strategy:
      matrix:
        package: [pipeline]
    name: build go binary
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18.1
      - name: Build binary
        working-directory: ./backend
        run: go build -o ./build/${{ matrix.package }} ./cmd/${{ matrix.package }}
