name: Frontend
on:
  push:
    branches:
      - "**"
      - "!main"
    paths:
      - "frontend/**"
      - ".github/workflows/frontend.yml"
jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Cache
        uses: actions/cache@v2.1.6
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install main dependencies
        run: cd frontend && yarn --prefer-offline
      - name: Runs linting
        run: cd frontend && yarn lint
      - name: Run Tests
        run: cd frontend && yarn test
      - name: Build Bundle
        run: cd frontend && CI=false yarn build
